version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - "post_db"
          - "comment_db"
      front_net:
    environment:
    - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
  ui:
    image: ${USERNAME}/ui:${IMAGE_VERSION}
    ports:
      - 9292:9292/tcp
    networks:
      front_net:
        aliases:
          - "ui"
    environment:
    - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui
  post:
    image: ${USERNAME}/post:${IMAGE_VERSION}
    networks:
      back_net:
        aliases:
          - "post"
      front_net:
        aliases:
          - "post"
    environment:
    - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    depends_on:
      - "post_db"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
  comment:
    image: ${USERNAME}/comment:${IMAGE_VERSION}
    networks:
      back_net:
        aliases:
          - "comment"
      front_net:
        aliases:
          - "comment"
    environment:
    - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
  prometheus:
    image: ${USERNAME}/prometheus
    ports:
      - '9090:9090'
    networks:
      back_net:
        aliases:
          - "prometheus"
      front_net:
        aliases:
          - "prometheus"
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    networks:
      back_net:
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'

volumes:
  post_db:
  prometheus_data:

networks:
  back_net:
  front_net:
